### PR TITLE
:construction: WIP: Fixing Refresh Token

### LINKED ISSUE #5: Token refresh not working → Unauthorized: invalid_token (AtProto::AuthError)
Tokens (via `omniauth-atproto`)  don't seem to get refreshed properly.  See code example below:

```ruby
private_key = OpenSSL::PKey::EC.new(Rails.application.credentials.atproto.private_key_pem)
credential = Credential.last # ActiveRecord object that has a did, token, refresh_token
pds_endpoint = DIDKit::Resolver.new.resolve_did(credential.did).pds_endpoint # https://porcini.us-east.host.bsky.network – in my case

client = AtProto::Client.new(
  access_token: credential.token,
  refresh_token: credential.refresh_token,
  private_key: private_key,
  refresh_token_url: pds_endpoint
)

credential.expired?
# => false

client.request(:get, "#{pds_endpoint}/xrpc/app.bsky.actor.getProfile", params: { actor: "marckohlbrugge.com" })
# => {"did"=>"did:plc:inatjjcm3vssdvkx27pvobhx",

# Wait for the token to expire

credential.expired?
# => true

client.request(:get, "#{pds_endpoint}/xrpc/app.bsky.actor.getProfile", params: { actor: "marckohlbrugge.com" })
# => Unauthorized: invalid_token (AtProto::AuthError)
```

Relevant code:

https://github.com/lasercatspro/atproto-ruby/blob/e3422f1fb8a4533f15da902df168c7f4d381fb19/lib/atproto_client/client.rb#L68-L91

Debugging statements:

```
[AtProto] Making GET request to https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile
[AtProto] Request headers will include DPoP token with access token: eyJ0eXAiOiJ...
[AtProto] Making GET request to https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=marckohlbrugge.com
[AtProto] Generating DPoP token for GET https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=marckohlbrugge.com
[AtProto] Using nonce: none
[AtProto] Creating DPoP token payload
[AtProto] Adding access token hash to payload
[AtProto] Generating access token hash
[AtProto] Encoding JWT token
[AtProto] DPoP token generated successfully
[AtProto] Creating new Request instance for GET https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=marckohlbrugge.com
[AtProto] Request initialized with headers: {"Authorization"=>"DPoP eyJ0eXAiOiJhdC…REMOVED", "DPoP"=>"eyJ0eXAiOiJ…REMOVED"}
[AtProto] Request body present: false
[AtProto] Sending request with DPoP token
[AtProto] Executing GET request to https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=marckohlbrugge.com
[AtProto] Request headers set: {"accept-encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "accept"=>["application/json"], "user-agent"=>["Ruby"], "host"=>["porcini.us-east.host.bsky.network"], "authorization"=>["DPoP eyJ0eXAiOiJhdCtqd3Qi…REMOVED"], "dpop"=>["eyJ0eXAiOiJkc…REMOVED"], "content-type"=>["application/json"]}
[AtProto] Making HTTP request...
[AtProto] Received response with status code: 401
[AtProto] Received client error response (401)
[AtProto] Response error: use_dpop_nonce
[AtProto] DPoP nonce required, raising error
[AtProto] Request failed with status: 401
[AtProto] First attempt failed, checking for new nonce
[AtProto] Checking response for new DPoP nonce
[AtProto] Updating nonce to: i4MOEyXv…REMOVED
[AtProto] Retrying request with new nonce
[AtProto] Making GET request to https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=marckohlbrugge.com
[AtProto] Generating DPoP token for GET https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=marckohlbrugge.com
[AtProto] Using nonce: i4MOEy…REMOVED
[AtProto] Creating DPoP token payload
[AtProto] Adding access token hash to payload
[AtProto] Generating access token hash
[AtProto] Adding nonce to payload: i4MO…REMOVED
[AtProto] Encoding JWT token
[AtProto] DPoP token generated successfully
[AtProto] Creating new Request instance for GET https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=marckohlbrugge.com
[AtProto] Request initialized with headers: {"Authorization"=>"DPoP eyJ0eXAiOiJ…REMOVED", "DPoP"=>"eyJ0eXAiO…REMOVED"}
[AtProto] Request body present: false
[AtProto] Sending request with DPoP token
[AtProto] Executing GET request to https://porcini.us-east.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=marckohlbrugge.com
[AtProto] Request headers set: {"accept-encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "accept"=>["application/json"], "user-agent"=>["Ruby"], "host"=>["porcini.us-east.host.bsky.network"], "authorization"=>["DPoP eyJ0eXA…REMOVED"], "dpop"=>["eyJ0eXA…REMOVED"], "content-type"=>["application/json"]}
[AtProto] Making HTTP request...
[AtProto] Received response with status code: 401
[AtProto] Received client error response (401)
[AtProto] Response error: invalid_token
[AtProto] Authentication error occurred
(blueskycounter):14:in `<main>': Unauthorized: invalid_token (AtProto::AuthError)
```

### PR DESCRIPTION
**Pull request by frabr**
Lot of api changes (needs 3 more arguments on init), interface needs inprovements, but token refresh seems to work.

Token refresh is "hard" enough to handle to be a usefull feature for this gem. It has a lot in common with token request (in oauth flow), especially the grant generation, so it would make sense to do it here, and let the omniauth strategy use the public method `token_params`

Currently it needs a lot of informations (especially if we want to handle non-bsky servers) as arguments to work. It would be nice to find a way to alleviate the initialization. Some clues to explore : 
- Deduce some params from others, it could be tempting to get the `refresh_token_url` from `site` or vice-versa but the format {site}/oauth/token seems not to be mandatory so it doesnt seem a good idea. We might also try to deduce `jwk` from `private key`.
- Pass some arguments at the method level instead of the instance, like client.refresh_access_token!(url: refresh_token_url)
- Use the `oauth/client-metadata.json` endpoint. It's tempting because it as a lot of the informations we need, but it feels strange to auto-request app on each client use.

I'll think about all this, feel free to give your thoughts about it

### CODE REVIEW

**Comment by frabr** [comment]
Ok, I am still working on it currently, but here is the design I came up with :
```ruby
# Initialize with just private key
client = AtProto::Client.new(private_key: key)
# Get initial access_token (to be used in oauth flow)
client.get_token!(code:, jwk:, client_id:, site:, endpoint:)
# Make requests
client.request(:get, "url", params:, body:)

# Or initialize with existing access token
client = AtProto::Client.new(private_key:, access_token:)
# Make requests
client.request(:get, "url", params:)
# Refresh token when needed
client.refresh_token!(refresh_token:, jwk:, client_id:, site:, endpoint: ) # + returns new tokens
```

This means that we will not support auto-refresh anymore. Instead users will have to catch TokenExpiredError and refresh it themselves :
```ruby
# I'm a bit approximate here...
def request
  @client.request(...)
rescue TokenExpiredError
  res = @client.refresh_token!(refresh_token:, jwk:, client_id:, site:, endpoint: )
  PdsToken.update!(refresh_token: res["refresh_token"])
  retry
end
```

@marckohlbrugge, as you're the most important user of this gem right now, tell me if you have remarks about it

**Comment by marckohlbrugge** [comment]
This seems like a good short-term solution 👍

For the long-term, I'd suggest implementing automatic token refresh functionality in the gem using a "Token Store" pattern. The Token Store would be a simple object with a predefined interface that handles token storage and updates. Here's what I envision:

```ruby
class AtProtoTokenStore
  def initialize(credential)
    @credential = credential
  end

  # Required method: Returns the current access token
  def access_token
    @credential.access_token
  end

  # Required method: Returns the current refresh token
  def refresh_token
    @credential.refresh_token
  end

  # Required method: Stores updated tokens
  def update_tokens(access_token:, refresh_token:)
    @credential.update!(
      access_token: access_token,
      refresh_token: refresh_token
    )
  end
end

# Example usage:
credential = Credential.find(user.id)
token_store = AtProtoTokenStore.new(credential)

client = AtProto::Client.new(token_store: token_store)
client.request(:get, "url", params: params)
```

The `AtProto::Client` would use this Token Store to:
1. Retrieve tokens when making requests
2. Automatically refresh tokens when they expire
3. Store the new tokens using the provided store

The beauty of this approach is its flexibility - developers can implement the Token Store however they want (ActiveRecord, Redis, plain Ruby object, etc.) as long as they implement these three required methods:
- `access_token`
- `refresh_token`
- `update_tokens(access_token:, refresh_token:)`

**Comment by marckohlbrugge** [comment]
And here's what a Redis-backed TokenStore could look like. To `AtProto::Client` it would be all the same.

```ruby
class RedisTokenStore
  def initialize(user_id, redis: Redis.new)
    @user_id = user_id
    @redis = redis
  end

  def access_token
    @redis.get("user:#{@user_id}:access_token")
  end

  def refresh_token
    @redis.get("user:#{@user_id}:refresh_token")
  end

  def update_tokens(access_token:, refresh_token:)
    @redis.multi do |multi|
      multi.set("user:#{@user_id}:access_token", access_token)
      multi.set("user:#{@user_id}:refresh_token", refresh_token)
    end
  end
end

# Usage with Redis:
token_store = RedisTokenStore.new(user.id)
client = AtProto::Client.new(token_store: token_store)
```

**Comment by marckohlbrugge** [comment]
The above approach could also be used to store and retrieve DPoP tokens.

**Comment by frabr** [comment]
Oh that's a good idea. I think I never used this pattern before, but it looks cool. We could offer this option at the same time as the more conventional interface.

**Pull request merged**
